import React, { useState } from 'react';
import { OutputItem } from '../types';
import { InteractiveChart } from './charts/InteractiveChart';
import { generateCodeForProcedure } from '../utils/codeGenerator';
import {
  FileText,
  Table as TableIcon,
  BarChart2,
  Trash2,
  Download,
  Printer,
  ChevronDown,
  Sparkles,
  Copy,
  Check,
  Code2,
  FileSpreadsheet,
  FileCode,
  FileJson
} from 'lucide-react';

interface OutputViewerProps {
  outputs: OutputItem[];
  projectName: string;
  onClearOutput: () => void;
  onExportHTML: () => void;
  onOpenAiReport?: () => void;
}

export const OutputViewer: React.FC<OutputViewerProps> = ({
  outputs,
  projectName,
  onClearOutput,
  onExportHTML,
  onOpenAiReport
}) => {
  const [activeItemId, setActiveItemId] = useState<string | null>(outputs[0]?.id || null);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [copiedCodeKey, setCopiedCodeKey] = useState<string | null>(null);
  const [activeCodeTab, setActiveCodeTab] = useState<{ [itemId: string]: 'spss' | 'python' | 'r' }>({});
  const [showCodeFor, setShowCodeFor] = useState<{ [itemId: string]: boolean }>({});

  const scrollToItem = (id: string) => {
    setActiveItemId(id);
    const el = document.getElementById(id);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  };

  const handleCopyTables = (item: OutputItem) => {
    let tsv = '';
    for (const t of item.tables) {
      tsv += `${t.title}\n`;
      for (const hRow of t.headers) {
        tsv += hRow.join('\t') + '\n';
      }
      for (const bRow of t.rows) {
        tsv += bRow.join('\t') + '\n';
      }
      tsv += '\n';
    }
    navigator.clipboard.writeText(tsv);
    setCopiedId(item.id);
    setTimeout(() => setCopiedId(null), 1500);
  };

  const handleCopyCode = (itemId: string, lang: 'spss' | 'python' | 'r', code: string) => {
    navigator.clipboard.writeText(code);
    setCopiedCodeKey(`${itemId}-${lang}`);
    setTimeout(() => setCopiedCodeKey(null), 1500);
  };

  const handleExportWord = () => {
    let content = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head><title>${projectName} - Statistical Report</title>
      <style>
        body { font-family: 'Times New Roman', serif; font-size: 11pt; color: #111; line-height: 1.5; padding: 20px; }
        h1 { font-size: 18pt; font-weight: bold; margin-bottom: 4px; }
        h2 { font-size: 14pt; font-weight: bold; margin-top: 20px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
        h3 { font-size: 12pt; font-weight: bold; margin-top: 14px; }
        table { border-collapse: collapse; width: 100%; margin: 12px 0; }
        th { border-top: 2px solid #000; border-bottom: 1px solid #000; font-weight: bold; padding: 6px 8px; font-size: 10pt; }
        td { padding: 5px 8px; font-size: 10pt; }
        tr:last-child td { border-bottom: 2px solid #000; }
        .meta { color: #555; font-size: 9pt; font-style: italic; margin-bottom: 20px; }
        .note { font-size: 9pt; font-style: italic; margin-top: 4px; }
      </style>
      </head><body>
      <h1>${projectName} — Statistical Output Report</h1>
      <div class="meta">Generated by Open SPSS Web (JaNuK / @lordskidgod) • ${new Date().toLocaleString()}</div>
    `;

    outputs.forEach(item => {
      content += `<h2>${item.procedure}: ${item.title}</h2>`;
      if (item.syntax) {
        content += `<div style="font-family: monospace; font-size: 9pt; background: #f4f4f4; padding: 8px; margin: 8px 0; border: 1px solid #ddd;">${item.syntax.replace(/\n/g, '<br/>')}</div>`;
      }
      item.tables.forEach(t => {
        content += `<h3>Table: ${t.title}</h3>`;
        if (t.subtitle) content += `<div style="font-size: 9.5pt; color: #444; margin-bottom: 4px;">${t.subtitle}</div>`;
        content += `<table><thead>`;
        t.headers.forEach(hRow => {
          content += `<tr>${hRow.map(h => `<th style="text-align:left;">${h}</th>`).join('')}</tr>`;
        });
        content += `</thead><tbody>`;
        t.rows.forEach(bRow => {
          content += `<tr>${bRow.map((c, i) => `<td style="text-align:${i > 0 && !isNaN(Number(c)) ? 'right' : 'left'}">${c ?? ''}</td>`).join('')}</tr>`;
        });
        content += `</tbody></table>`;
        if (t.footnotes && t.footnotes.length > 0) {
          t.footnotes.forEach(fn => {
            content += `<div class="note">Note: ${fn}</div>`;
          });
        }
      });
    });

    content += `</body></html>`;
    const blob = new Blob([content], { type: 'application/msword;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectName.replace(/\s+/g, '_')}_Report.doc`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportJSON = () => {
    const jsonStr = JSON.stringify({ project: projectName, exportedAt: new Date().toISOString(), outputs }, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectName.replace(/\s+/g, '_')}_Outputs.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="output-viewer-layout">
      {/* Left Outline Tree */}
      <div className="output-outline-tree">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid var(--border-subtle)', marginBottom: '10px' }}>
          <span style={{ fontSize: '0.74rem', fontWeight: 700, color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
            Output Outline
          </span>
          {outputs.length > 0 && (
            <button className="tool-btn" title="Clear All Outputs" onClick={onClearOutput} style={{ padding: '2px 5px', color: 'var(--danger)', fontSize: '0.7rem' }}>
              <Trash2 size={12} /> Clear
            </button>
          )}
        </div>

        {outputs.length === 0 ? (
          <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', padding: '16px 0', textAlign: 'center' }}>
            No outputs generated yet
          </div>
        ) : (
          outputs.map(item => (
            <div key={item.id} style={{ display: 'flex', flexDirection: 'column', gap: '2px', marginBottom: '6px' }}>
              <div
                className={`tree-node ${activeItemId === item.id ? 'active' : ''}`}
                onClick={() => scrollToItem(item.id)}
              >
                <ChevronDown size={13} style={{ opacity: 0.6 }} />
                <FileText size={13} style={{ color: 'var(--primary)' }} />
                <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontWeight: 600 }}>{item.procedure}</span>
              </div>

              {/* Sub-items */}
              <div style={{ paddingLeft: '22px', display: 'flex', flexDirection: 'column', gap: '2px' }}>
                {item.tables.map((t, idx) => (
                  <div
                    key={idx}
                    className="tree-node"
                    style={{ fontSize: '0.74rem', padding: '3px 8px' }}
                    onClick={() => scrollToItem(item.id)}
                  >
                    <TableIcon size={11} style={{ opacity: 0.6 }} />
                    <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{t.title}</span>
                  </div>
                ))}
                {item.charts.map((c, idx) => (
                  <div
                    key={idx}
                    className="tree-node"
                    style={{ fontSize: '0.74rem', padding: '3px 8px' }}
                    onClick={() => scrollToItem(item.id)}
                  >
                    <BarChart2 size={11} style={{ opacity: 0.6 }} />
                    <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{c.title}</span>
                  </div>
                ))}
              </div>
            </div>
          ))
        )}
      </div>

      {/* Right Output Content Pane */}
      <div className="output-content-area">
        {/* Output Action Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 18px', background: 'var(--bg-surface)', border: '1px solid var(--border-color)', borderRadius: '10px', boxShadow: 'var(--shadow-xs)', flexWrap: 'wrap', gap: '10px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <span style={{ fontSize: '0.88rem', fontWeight: 700 }}>
              Statistical Output Document
            </span>
            <span style={{ color: 'var(--text-muted)' }}>•</span>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
              Project: <b>{projectName}</b> ({outputs.length} procedure{outputs.length === 1 ? '' : 's'})
            </span>
          </div>

          <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
            <button className="btn btn-secondary" onClick={onExportHTML} title="Export as APA 7th formatted HTML document" style={{ fontSize: '0.74rem', padding: '4px 8px' }}>
              <Download size={13} /> HTML Report
            </button>
            <button className="btn btn-secondary" onClick={handleExportWord} title="Export as Word document (.doc)" style={{ fontSize: '0.74rem', padding: '4px 8px' }}>
              <FileText size={13} /> Word Doc
            </button>
            <button className="btn btn-secondary" onClick={handleExportJSON} title="Export raw JSON output data" style={{ fontSize: '0.74rem', padding: '4px 8px' }}>
              <FileJson size={13} /> JSON
            </button>
            <button className="btn btn-secondary" onClick={handlePrint} title="Print or Save as PDF" style={{ fontSize: '0.74rem', padding: '4px 8px' }}>
              <Printer size={13} /> Print / PDF
            </button>
          </div>
        </div>

        {outputs.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '70px 24px', background: 'var(--bg-surface)', borderRadius: '12px', border: '1px dashed var(--border-color)', boxShadow: 'var(--shadow-xs)' }}>
            <div style={{ width: '60px', height: '60px', borderRadius: '14px', background: 'var(--primary-light)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px auto', color: 'var(--primary)' }}>
              <Sparkles size={28} />
            </div>
            <h3 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '8px', color: 'var(--text-primary)' }}>
              Ready for Statistical Analysis
            </h3>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.86rem', maxWidth: '520px', margin: '0 auto 24px auto', lineHeight: 1.6 }}>
              Select any statistical procedure from the <b>Analyze</b> menu (such as Frequencies, Descriptives, Independent T-Test, One-Way ANOVA, Regression, or Factor Analysis) to generate APA 7th edition formatted pivot tables, interactive charts, and multi-language reproducible scripts.
            </p>
          </div>
        ) : (
          outputs.map(item => {
            const isCodeOpen = showCodeFor[item.id] || false;
            const curLang = activeCodeTab[item.id] || 'spss';
            const codeTranslations = generateCodeForProcedure(item.procedure, {
              variables: item.tables[0]?.headers[0]?.slice(1) || []
            });

            return (
              <div key={item.id} id={item.id} className="output-card">
                <div className="output-card-header">
                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                      <h3 className="output-card-title">{item.procedure}</h3>
                      <span className="brand-badge" style={{ fontSize: '0.62rem', padding: '1.5px 6px' }}>APA 7th</span>
                    </div>
                    <span style={{ fontSize: '0.82rem', color: 'var(--text-secondary)' }}>{item.title}</span>
                  </div>

                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                    <button
                      className={`btn ${isCodeOpen ? 'btn-primary' : 'btn-secondary'}`}
                      onClick={() => setShowCodeFor(prev => ({ ...prev, [item.id]: !isCodeOpen }))}
                      style={{ fontSize: '0.74rem', padding: '3px 8px', gap: '5px' }}
                      title="View Reproducible Code (SPSS Syntax, Python & R)"
                    >
                      <Code2 size={12} />
                      <span>{isCodeOpen ? 'Hide Code' : 'Python / R / Syntax'}</span>
                    </button>

                    <button
                      className="btn btn-secondary"
                      onClick={() => handleCopyTables(item)}
                      style={{ fontSize: '0.74rem', padding: '3px 8px' }}
                      title="Copy all tables as tab-separated values (ready to paste into Excel or Word)"
                    >
                      {copiedId === item.id ? <Check size={12} style={{ color: '#10b981' }} /> : <Copy size={12} />}
                      <span>{copiedId === item.id ? 'Copied' : 'Copy Tables'}</span>
                    </button>
                    <span style={{ fontSize: '0.76rem', color: 'var(--text-muted)' }}>{item.timestamp}</span>
                  </div>
                </div>

                {/* Multi-Language Code Translation Drawer */}
                {isCodeOpen && (
                  <div style={{ margin: '12px 0', background: 'var(--bg-surface-subtle)', borderRadius: '8px', border: '1px solid var(--border-color)', overflow: 'hidden' }}>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid var(--border-color)', background: 'var(--bg-surface)', padding: '4px 10px' }}>
                      <div style={{ display: 'flex', gap: '4px' }}>
                        <button
                          onClick={() => setActiveCodeTab(prev => ({ ...prev, [item.id]: 'spss' }))}
                          style={{
                            padding: '4px 10px',
                            fontSize: '0.72rem',
                            borderRadius: '4px',
                            fontWeight: curLang === 'spss' ? 700 : 500,
                            background: curLang === 'spss' ? 'var(--primary)' : 'transparent',
                            color: curLang === 'spss' ? 'white' : 'var(--text-secondary)',
                            border: 'none',
                            cursor: 'pointer'
                          }}
                        >
                          SPSS Syntax
                        </button>
                        <button
                          onClick={() => setActiveCodeTab(prev => ({ ...prev, [item.id]: 'python' }))}
                          style={{
                            padding: '4px 10px',
                            fontSize: '0.72rem',
                            borderRadius: '4px',
                            fontWeight: curLang === 'python' ? 700 : 500,
                            background: curLang === 'python' ? 'var(--primary)' : 'transparent',
                            color: curLang === 'python' ? 'white' : 'var(--text-secondary)',
                            border: 'none',
                            cursor: 'pointer'
                          }}
                        >
                          Python (pandas/scipy)
                        </button>
                        <button
                          onClick={() => setActiveCodeTab(prev => ({ ...prev, [item.id]: 'r' }))}
                          style={{
                            padding: '4px 10px',
                            fontSize: '0.72rem',
                            borderRadius: '4px',
                            fontWeight: curLang === 'r' ? 700 : 500,
                            background: curLang === 'r' ? 'var(--primary)' : 'transparent',
                            color: curLang === 'r' ? 'white' : 'var(--text-secondary)',
                            border: 'none',
                            cursor: 'pointer'
                          }}
                        >
                          R Script
                        </button>
                      </div>

                      <button
                        className="btn btn-secondary"
                        onClick={() => handleCopyCode(item.id, curLang, codeTranslations[curLang])}
                        style={{ fontSize: '0.70rem', padding: '2px 8px', gap: '4px' }}
                      >
                        {copiedCodeKey === `${item.id}-${curLang}` ? <Check size={11} style={{ color: '#10b981' }} /> : <Copy size={11} />}
                        <span>{copiedCodeKey === `${item.id}-${curLang}` ? 'Copied' : `Copy ${curLang.toUpperCase()}`}</span>
                      </button>
                    </div>

                    <pre style={{ margin: 0, padding: '12px 14px', fontFamily: 'JetBrains Mono, monospace', fontSize: '0.76rem', color: 'var(--text-primary)', overflowX: 'auto', background: 'var(--bg-main)' }}>
                      <code>{codeTranslations[curLang]}</code>
                    </pre>
                  </div>
                )}

                {/* Syntax Log Block if code is closed */}
                {!isCodeOpen && item.syntax && (
                  <div className="spss-syntax-block">
                    <div style={{ fontWeight: 700, fontSize: '0.7rem', color: 'var(--primary)', marginBottom: '4px', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
                      Log & Syntax Executed
                    </div>
                    <code>{item.syntax}</code>
                  </div>
                )}

                {/* Tables */}
                {item.tables.map((table, tIdx) => (
                  <div key={tIdx} style={{ margin: '22px 0' }}>
                    <div style={{ marginBottom: '6px' }}>
                      <h4 style={{ fontSize: '0.94rem', fontWeight: 700, color: 'var(--text-primary)', letterSpacing: '-0.01em' }}>
                        {table.title}
                      </h4>
                      {table.subtitle && (
                        <div style={{ fontSize: '0.78rem', color: 'var(--text-secondary)' }}>
                          {table.subtitle}
                        </div>
                      )}
                    </div>

                    <div style={{ overflowX: 'auto' }}>
                      <table className="spss-pivot-table">
                        <thead>
                          {table.headers.map((hRow, hrIdx) => (
                            <tr key={hrIdx}>
                              {hRow.map((h, hcIdx) => (
                                <th key={hcIdx}>{h}</th>
                              ))}
                            </tr>
                          ))}
                        </thead>
                        <tbody>
                          {table.rows.map((bRow, brIdx) => (
                            <tr key={brIdx}>
                              {bRow.map((cell, bcIdx) => {
                                const isNum = typeof cell === 'number' || (!isNaN(Number(cell)) && cell !== '' && typeof cell === 'string' && !cell.includes('%'));
                                return (
                                  <td key={bcIdx} style={{ textAlign: isNum && bcIdx > 0 ? 'right' : 'left' }}>
                                    {cell !== undefined ? cell : ''}
                                  </td>
                                );
                              })}
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>

                    {table.footnotes && table.footnotes.length > 0 && (
                      <div style={{ marginTop: '6px', fontSize: '0.76rem', color: 'var(--text-secondary)', lineHeight: 1.5 }}>
                        {table.footnotes.map((fn, fIdx) => (
                          <div key={fIdx}><i>Note:</i> {fn}</div>
                        ))}
                      </div>
                    )}
                  </div>
                ))}

                {/* Charts */}
                {item.charts.map((chart, cIdx) => (
                  <div key={cIdx}>
                    <InteractiveChart chart={chart} />
                  </div>
                ))}
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};
